version: '3.8'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-online-store
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
